### ISSUE TITLE
Error when trying to run abiopen.py

### ISSUE THREAD

**Issue by ssh77** [abinit/abipy#199]
No matter what I try I get this error message which is annoying since I cannot make use of abipy due to this.

Traceback (most recent call last):
  File "/home/universe/.local/bin/abiopen.py", line 15, in <module>
    from abipy import abilab
  File "/home/universe/.local/lib/python3.7/site-packages/abipy/__init__.py", line 18, in <module>
    from abipy.core import release
  File "/home/universe/.local/lib/python3.7/site-packages/abipy/core/__init__.py", line 3, in <module>
    from .kpoints import *
  File "/home/universe/.local/lib/python3.7/site-packages/abipy/core/kpoints.py", line 18, in <module>
    from abipy.iotools import ETSF_Reader
  File "/home/universe/.local/lib/python3.7/site-packages/abipy/iotools/__init__.py", line 4, in <module>
    import pymatgen.io.abinit.netcdf as ionc
  File "/home/universe/.local/lib/python3.7/site-packages/pymatgen/io/abinit/__init__.py", line 6, in <module>
    from .netcdf import *
  File "/home/universe/.local/lib/python3.7/site-packages/pymatgen/io/abinit/netcdf.py", line 41, in <module>
    import netCDF4
  File "/home/universe/.local/lib/python3.7/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
  File "netCDF4/_netCDF4.pyx", line 1213, in init netCDF4._netCDF4
  File "/home/universe/.local/lib/python3.7/site-packages/cftime/__init__.py", line 1, in <module>
    from ._cftime import utime, JulianDayFromDate, DateFromJulianDay
  File "__init__.pxd", line 918, in init cftime._cftime
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

Could you fix this issue in an update or let me know how to resolve it.
I use Fedora Scientific.

**Comment by gmatteo** [comment]
It's likely an incompatibility between your version of numpy and netcdf4.
A similar problem with a possibile solution is reported [here](https://github.com/scikit-learn-contrib/hdbscan/issues/272#issuecomment-534210100)

**Comment by ssh77** [comment]
Thanks! That helped solve this issue.
