### ISSUE TITLE
module 'pymatgen.io.abinit.netcdf' has no attribute 'ETSF_Reader'

### ISSUE THREAD

**Issue by abdelghany0** [abinit/abipy#274]
Dear Abipy Developers,

I faced this issue with the Yambopy code but it looks like an Abipy issue. 

When I run the script  python gw_bn.py the following error shows up:

```
Traceback (most recent call last):
  File "/rhome/Ragab/11-yambopy/3run/plot-qp.py", line 53, in <module>
    ks_bs, qp_bs = ydb.interpolate(lat,path,what='QP+KS',lpratio=20)
  File "/usr/local/anaconda3/envs/triqs/lib/python3.9/site-packages/yambopy-0.2.0-py3.9.egg/yambopy/dbs/qpdb.py", line 275, in interpolate
    from abipy.core.skw import SkwInterpolator
  File "/usr/local/anaconda3/envs/triqs/lib/python3.9/site-packages/abipy/__init__.py", line 17, in <module>
    from abipy.core import release
  File "/usr/local/anaconda3/envs/triqs/lib/python3.9/site-packages/abipy/core/__init__.py", line 3, in <module>
    from .kpoints import *
  File "/usr/local/anaconda3/envs/triqs/lib/python3.9/site-packages/abipy/core/kpoints.py", line 19, in <module>
    from abipy.iotools import ETSF_Reader
  File "/usr/local/anaconda3/envs/triqs/lib/python3.9/site-packages/abipy/iotools/__init__.py", line 17, in <module>
    class ETSF_Reader(ionc.ETSF_Reader):
AttributeError: module 'pymatgen.io.abinit.netcdf' has no attribute 'ETSF_Reader'
```

How can I solve this issue? 

Thanks

Ragab

**Comment by sphuber** [comment]
This was reported here https://github.com/abinit/abipy/issues/258 and should be fixed by https://github.com/abinit/abipy/commit/d172fb8ab716ad34fcaef87d736f4388ccd4d845

**Comment by sphuber** [comment]
That depends on what triggered the exception. You only show the last part of the stack trace. 

The problem is that the `pymatgen.io.vasp` module relies on this `potcar_summary_stats.json.gz` file being there, but it isn't. The problem was that `abipy` was always importing this module, and so always excepting, even if you are not using that part.

Therefore, in https://github.com/abinit/abipy/commit/e3d37767d82bbf993168b8523076ea9d35b88bb8 I simply moved the imports to inside the methods where they are used. After that, you can use `abipy` again. It is on the `develop` branch, so just check that out and install it.

Of course, if you then actually import the pymatgen module, that will still probably except because it cannot find the `.json.gz` file. But that is a bug with `pymatgen` I would say.
