### ISSUE TITLE
keyword argument 'kw_only'

### ISSUE THREAD

**Issue by yuchen230** [abinit/abipy#295]
An error occurs when executing this line of code: abiopen.py tbase1_1.abo --expose --seaborn

Traceback (most recent call last):
  File "/home/pc/.local/bin/abiopen.py", line 21, in <module>
    from abipy import abilab
  File "/home/pc/.local/lib/python3.9/site-packages/abipy/abilab.py", line 50, in <module>
    from abipy.electrons.gwr import GwrFile
  File "/home/pc/.local/lib/python3.9/site-packages/abipy/electrons/gwr.py", line 42, in <module>
    @dataclasses.dataclass(kw_only=True)
TypeError: dataclass() got an unexpected keyword argument 'kw_only'

**Comment by gmatteo** [comment]
We’ve dropped support for Python 3.9; you need at least Python 3.10
