### ISSUE TITLE
ValueError: Unknown DictSet MPStaticSet, must be one of ['DictSet']

### ISSUE THREAD

**Issue by Guodonglin-cqust** [abinit/abipy#302]
(base) cqwl222@cqwl222:~/Documents$ **abinp.py vasp POSCAR**
/home/cqwl222/anaconda3/lib/python3.10/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
Traceback (most recent call last):
  File "/home/cqwl222/anaconda3/bin/abinp.py", line 503, in <module>
    sys.exit(main())
  File "/home/cqwl222/anaconda3/lib/python3.10/site-packages/monty/functools.py", line 278, in wrapper
    sys.exit(main())
  File "/home/cqwl222/anaconda3/bin/abinp.py", line 499, in main
    return globals()["abinp_" + options.command](options)
  File "/home/cqwl222/anaconda3/bin/abinp.py", line 283, in abinp_vasp
    cls = vasp_dict_set_cls(options.dict_set)
  File "/home/cqwl222/anaconda3/bin/abinp.py", line 43, in vasp_dict_set_cls
    **raise ValueError(f"Unknown DictSet {s}, must be one of {valid_keys}")
ValueError: Unknown DictSet MPStaticSet, must be one of ['DictSet']**

The POSCAR like this:

Se1 Sn1                                 
   1.00000000000000     
     3.8828267224496016    0.0000000000000000    0.0000000000000000
    -1.9414133612248008    3.3626265801344242    0.0000000000000000
     0.0000000000000000    0.0000000000000000   30.0000000000000000
   Se   Sn
     1     1
Direct
 -0.0000000000000000 -0.0000000000000000  0.5001330230972471
  0.3333333333333357  0.6666666666666643  0.5518209998607532
 
  0.00000000E+00  0.00000000E+00  0.00000000E+00
  0.00000000E+00  0.00000000E+00  0.00000000E+00

**Comment by gmatteo** [comment]
Thanks for reporting the problem.
I'm just committed a fix, see https://github.com/abinit/abipy/commit/efc58b5fde5d672c867ddc83ee5dafef87b75b75

in particular the changes in `abinp.py`

**Comment by Guodonglin-cqust** [comment]
pip uninstall abipy

pip install abipy --user


**(base) cqwl222@cqwl222:~/Public$ abinp.py vasp POSCAR**
/home/cqwl222/anaconda3/lib/python3.10/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
Traceback (most recent call last):
  File "/home/cqwl222/.local/bin/abinp.py", line 503, in <module>
    sys.exit(main())
  File "/home/cqwl222/anaconda3/lib/python3.10/site-packages/monty/functools.py", line 278, in wrapper
    sys.exit(main())
  File "/home/cqwl222/.local/bin/abinp.py", line 499, in main
    return globals()["abinp_" + options.command](options)
  File "/home/cqwl222/.local/bin/abinp.py", line 283, in abinp_vasp
    cls = vasp_dict_set_cls(options.dict_set)
  File "/home/cqwl222/.local/bin/abinp.py", line 43, in vasp_dict_set_cls
    **raise ValueError(f"Unknown DictSet {s}, must be one of {valid_keys}")
ValueError: Unknown DictSet MPStaticSet, must be one of ['DictSet']**
(base) cqwl222@cqwl222:~/Public$
  

I find the problem exists
